/**
 * Mock Course Data
 * Temporary mock data for courses until API is ready
 */

import { Course } from '@/types/course.types';

export const mockCourses: Course[] = [
  {
    id: '1',
    title: 'Complete React Native Development',
    description: 'Build mobile apps with React Native from scratch. Learn hooks, navigation, state management, and more.',
    thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800',
    instructor: 'John Smith',
    instructorAvatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    price: 799000,
    originalPrice: 1299000,
    rating: 4.8,
    totalReviews: 2458,
    totalStudents: 15420,
    duration: '24h 30m',
    totalLessons: 185,
    level: 'INTERMEDIATE',
    category: 'PROGRAMMING',
    tags: ['React Native', 'JavaScript', 'Mobile'],
    isFeatured: true,
    isNew: false,
    createdAt: '2024-01-15',
    updatedAt: '2024-06-20',
  },
  {
    id: '2',
    title: 'UI/UX Design Masterclass',
    description: 'Master the art of designing beautiful and functional user interfaces. Figma, Adobe XD, and more.',
    thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800',
    instructor: 'Sarah Johnson',
    instructorAvatar: 'https://randomuser.me/api/portraits/women/2.jpg',
    price: 599000,
    originalPrice: 999000,
    rating: 4.9,
    totalReviews: 1876,
    totalStudents: 12350,
    duration: '18h 45m',
    totalLessons: 142,
    level: 'BEGINNER',
    category: 'DESIGN',
    tags: ['UI/UX', 'Figma', 'Design'],
    isFeatured: true,
    isNew: true,
    createdAt: '2024-05-10',
    updatedAt: '2024-06-18',
  },
  {
    id: '3',
    title: 'Python for Data Science',
    description: 'Learn Python programming and data science fundamentals. NumPy, Pandas, Matplotlib, and Machine Learning.',
    thumbnail: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800',
    instructor: 'Michael Chen',
    instructorAvatar: 'https://randomuser.me/api/portraits/men/3.jpg',
    price: 899000,
    originalPrice: 1499000,
    rating: 4.7,
    totalReviews: 3245,
    totalStudents: 21500,
    duration: '32h 15m',
    totalLessons: 248,
    level: 'BEGINNER',
    category: 'DATA_SCIENCE',
    tags: ['Python', 'Data Science', 'Machine Learning'],
    isFeatured: false,
    isNew: false,
    createdAt: '2023-08-20',
    updatedAt: '2024-04-15',
  },
  {
    id: '4',
    title: 'Digital Marketing Complete Guide',
    description: 'Master digital marketing strategies including SEO, Social Media, Email Marketing, and Google Ads.',
    thumbnail: 'https://images.unsplash.com/photo-1432888622747-4eb9a8f5a70d?w=800',
    instructor: 'Emily Davis',
    instructorAvatar: 'https://randomuser.me/api/portraits/women/4.jpg',
    price: 499000,
    originalPrice: 799000,
    rating: 4.6,
    totalReviews: 1523,
    totalStudents: 9870,
    duration: '15h 20m',
    totalLessons: 98,
    level: 'BEGINNER',
    category: 'MARKETING',
    tags: ['Marketing', 'SEO', 'Social Media'],
    isFeatured: false,
    isNew: true,
    createdAt: '2024-04-01',
    updatedAt: '2024-06-10',
  },
  {
    id: '5',
    title: 'Advanced Node.js & Express',
    description: 'Build scalable backend applications with Node.js, Express, MongoDB, and GraphQL.',
    thumbnail: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=800',
    instructor: 'David Wilson',
    instructorAvatar: 'https://randomuser.me/api/portraits/men/5.jpg',
    price: 699000,
    originalPrice: 1199000,
    rating: 4.8,
    totalReviews: 2134,
    totalStudents: 14280,
    duration: '28h 40m',
    totalLessons: 195,
    level: 'ADVANCED',
    category: 'PROGRAMMING',
    tags: ['Node.js', 'Express', 'Backend'],
    isFeatured: true,
    isNew: false,
    createdAt: '2023-11-15',
    updatedAt: '2024-05-22',
  },
  {
    id: '6',
    title: 'Business Strategy & Management',
    description: 'Learn essential business strategies, leadership skills, and management techniques.',
    thumbnail: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800',
    instructor: 'Jennifer Brown',
    instructorAvatar: 'https://randomuser.me/api/portraits/women/6.jpg',
    price: 549000,
    originalPrice: 899000,
    rating: 4.5,
    totalReviews: 987,
    totalStudents: 6540,
    duration: '12h 30m',
    totalLessons: 76,
    level: 'INTERMEDIATE',
    category: 'BUSINESS',
    tags: ['Business', 'Strategy', 'Leadership'],
    isFeatured: false,
    isNew: false,
    createdAt: '2023-09-10',
    updatedAt: '2024-03-18',
  },
  {
    id: '7',
    title: 'Flutter Mobile Development',
    description: 'Build beautiful cross-platform mobile apps with Flutter and Dart programming language.',
    thumbnail: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800',
    instructor: 'Alex Turner',
    instructorAvatar: 'https://randomuser.me/api/portraits/men/7.jpg',
    price: 749000,
    originalPrice: 1299000,
    rating: 4.9,
    totalReviews: 1876,
    totalStudents: 11230,
    duration: '26h 15m',
    totalLessons: 172,
    level: 'INTERMEDIATE',
    category: 'PROGRAMMING',
    tags: ['Flutter', 'Dart', 'Mobile'],
    isFeatured: true,
    isNew: true,
    createdAt: '2024-02-28',
    updatedAt: '2024-06-15',
  },
  {
    id: '8',
    title: 'English for Business Communication',
    description: 'Improve your business English skills for professional communication and presentations.',
    thumbnail: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800',
    instructor: 'Lisa Anderson',
    instructorAvatar: 'https://randomuser.me/api/portraits/women/8.jpg',
    price: 399000,
    originalPrice: 599000,
    rating: 4.4,
    totalReviews: 756,
    totalStudents: 5420,
    duration: '10h 45m',
    totalLessons: 64,
    level: 'BEGINNER',
    category: 'LANGUAGE',
    tags: ['English', 'Business', 'Communication'],
    isFeatured: false,
    isNew: false,
    createdAt: '2023-07-20',
    updatedAt: '2024-02-10',
  },
];

export const courseCategories = [
  { key: 'ALL', label: 'All', icon: 'apps' },
  { key: 'PROGRAMMING', label: 'Programming', icon: 'code-slash' },
  { key: 'DESIGN', label: 'Design', icon: 'color-palette' },
  { key: 'DATA_SCIENCE', label: 'Data Science', icon: 'analytics' },
  { key: 'BUSINESS', label: 'Business', icon: 'briefcase' },
  { key: 'MARKETING', label: 'Marketing', icon: 'megaphone' },
  { key: 'LANGUAGE', label: 'Language', icon: 'language' },
] as const;

export const courseLevels = [
  { key: 'ALL', label: 'All Levels' },
  { key: 'BEGINNER', label: 'Beginner' },
  { key: 'INTERMEDIATE', label: 'Intermediate' },
  { key: 'ADVANCED', label: 'Advanced' },
] as const;

export const sortOptions = [
  { key: 'popular', label: 'Most Popular' },
  { key: 'newest', label: 'Newest' },
  { key: 'rating', label: 'Highest Rated' },
  { key: 'price_low', label: 'Price: Low to High' },
  { key: 'price_high', label: 'Price: High to Low' },
] as const;
